### ISSUE TITLE
Authorization header case problem

### ISSUE THREAD

**Issue by sqpierce** [Jaymon/endpoints#78]
Note that the Authorization header is customarily written as it is here, but the method that extracts it in endpoints only accepts all lower case. Perhaps we could make this case insensitive?

https://github.com/firstopinion/endpoints/blob/master/endpoints/http.py#L1080-L1086

**Comment by Jaymon** [comment]
It's case-insensitive already, the `Request` class extends `Http`, which instantiates a `Headers` instance, which is nicely [summarized in the class description](https://github.com/Jaymon/endpoints/blob/master/endpoints/http.py#L31-L49) about how it handles cases. It's also [well tested](https://github.com/Jaymon/endpoints/blob/master/tests/http_test.py#L16)

I've updated internal code to use `Request.access_token` and tests are passing as expected
